/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.EditarTexto;

import java.awt.Font;
import java.awt.Window;
import javax.swing.JComboBox;
import javax.swing.SwingUtilities;

/**
 *
 * @author 2dam
 */
public class Fuente2 extends javax.swing.JPanel {

   public String tamano(){
       String seleccion= String.valueOf(TamañoOpciones.getSelectedItem());
       return seleccion;
   }

    /**
     * Creates new form Fuente2
     */
    public Fuente2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelfuente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        FuenteOpciones = new javax.swing.JComboBox<>();
        EfectosOpciones = new javax.swing.JComboBox<>();
        TamañoOpciones = new javax.swing.JComboBox<>();
        VistaPrevia = new javax.swing.JLabel();

        jLabel1.setText("Fuente");

        jLabel2.setText("Efectos");

        jLabel3.setText("Tamaño");

        jButton1.setText("Acceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        FuenteOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "Lucida Console", "Noto Sans", "Segoe UI" }));
        FuenteOpciones.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                FuenteOpcionesX(evt);
            }
        });
        FuenteOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuenteOpcionesActionPerformed(evt);
            }
        });

        EfectosOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "Plain", "Bold", "Italic" }));
        EfectosOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EfectosOpcionesActionPerformed(evt);
            }
        });

        TamañoOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "10", "15", "20" }));
        TamañoOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TamañoOpcionesActionPerformed(evt);
            }
        });

        VistaPrevia.setText("Vista previa");

        javax.swing.GroupLayout panelfuenteLayout = new javax.swing.GroupLayout(panelfuente);
        panelfuente.setLayout(panelfuenteLayout);
        panelfuenteLayout.setHorizontalGroup(
            panelfuenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfuenteLayout.createSequentialGroup()
                .addGroup(panelfuenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelfuenteLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(Cancelar))
                    .addGroup(panelfuenteLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(panelfuenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EfectosOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VistaPrevia))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelfuenteLayout.createSequentialGroup()
                .addGroup(panelfuenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelfuenteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(FuenteOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelfuenteLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1)))
                .addGap(46, 46, 46)
                .addGroup(panelfuenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelfuenteLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(35, 35, 35))
                    .addGroup(panelfuenteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TamañoOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        panelfuenteLayout.setVerticalGroup(
            panelfuenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfuenteLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(panelfuenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(55, 55, 55)
                .addGroup(panelfuenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EfectosOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TamañoOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FuenteOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(VistaPrevia)
                .addGap(18, 18, 18)
                .addGroup(panelfuenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Cancelar))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelfuente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelfuente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        Window w = SwingUtilities.getWindowAncestor(Fuente2.this);
        w.setVisible(false);
    }//GEN-LAST:event_CancelarActionPerformed

    private void FuenteOpcionesX(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_FuenteOpcionesX
        // TODO add your handling code here:
    }//GEN-LAST:event_FuenteOpcionesX

    private void FuenteOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuenteOpcionesActionPerformed

        String seleccion= String.valueOf(FuenteOpciones.getSelectedItem());
         if(seleccion.equals("Lucida Console")){
           VistaPrevia.setFont(new Font("Lucida Console", VistaPrevia.getFont().getStyle(),VistaPrevia.getFont().getSize())); 
        }
         if(seleccion.equals("Noto Sans")){
           VistaPrevia.setFont(new Font("Noto Sans", VistaPrevia.getFont().getStyle(),VistaPrevia.getFont().getSize())); 
        }
         if(seleccion.equals("Segoe UI")){
           VistaPrevia.setFont(new Font("Segoe UI", VistaPrevia.getFont().getStyle(),VistaPrevia.getFont().getSize())); 
        }
    }//GEN-LAST:event_FuenteOpcionesActionPerformed

    private void TamañoOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TamañoOpcionesActionPerformed
       //Tiene que meter en una variable el valor del comboBox 
        String seleccion= String.valueOf(TamañoOpciones.getSelectedItem());
         if(seleccion.equals("5")){
           VistaPrevia.setFont(new Font(VistaPrevia.getFont().getFontName(), VistaPrevia.getFont().getStyle(),5)); 
        }
        if(seleccion.equals("10")){
           VistaPrevia.setFont(new Font(VistaPrevia.getFont().getFontName(), VistaPrevia.getFont().getStyle(),10)); 
        }
         if(seleccion.equals("15")){
           VistaPrevia.setFont(new Font(VistaPrevia.getFont().getFontName(), VistaPrevia.getFont().getStyle(),15)); 
        }
          if(seleccion.equals("20")){
           VistaPrevia.setFont(new Font(VistaPrevia.getFont().getFontName(), VistaPrevia.getFont().getStyle(),20)); 
        }
        
    }//GEN-LAST:event_TamañoOpcionesActionPerformed

    private void EfectosOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EfectosOpcionesActionPerformed
       String seleccion= String.valueOf(EfectosOpciones.getSelectedItem());
         if(seleccion.equals("Italic")){
           VistaPrevia.setFont(new Font("Segoe", Font.ITALIC,VistaPrevia.getFont().getSize())); 
        }
         if(seleccion.equals("Plain")){
           VistaPrevia.setFont(new Font("Segoe", Font.PLAIN,VistaPrevia.getFont().getSize())); 
        }
         if(seleccion.equals("Bold")){
           VistaPrevia.setFont(new Font("Segoe", Font.BOLD,VistaPrevia.getFont().getSize())); 
        }
        
    }//GEN-LAST:event_EfectosOpcionesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EditorTexto.AreaTexto.setFont(new Font (VistaPrevia.getFont().getFontName(), VistaPrevia.getFont().getStyle(),VistaPrevia.getFont().getSize()));
        Window w = SwingUtilities.getWindowAncestor(Fuente2.this);
        w.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JComboBox<String> EfectosOpciones;
    private javax.swing.JComboBox<String> FuenteOpciones;
    private javax.swing.JComboBox<String> TamañoOpciones;
    private javax.swing.JLabel VistaPrevia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelfuente;
    // End of variables declaration//GEN-END:variables
}
